# syntax=docker/dockerfile:1

###############################################################################
# UAE7Guard — production image for Next.js 16 (standalone output).
# Runs on ANY container host: Fly.io, Railway, Render, DigitalOcean App
# Platform, Google Cloud Run, AWS ECS/App Runner, Azure Container Apps,
# Kubernetes, or a plain VPS with Docker. (No Vercel required.)
#
#   docker build -t uae7guard .
#   docker run -p 3000:3000 --env-file .env.local uae7guard
###############################################################################

# 1) Install dependencies only when lockfile changes -------------------------
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# 2) Build the application ---------------------------------------------------
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# 3) Minimal runtime image ---------------------------------------------------
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Run as a non-root user.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Standalone output does NOT bundle static assets or /public — copy them in.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:' + (process.env.PORT || 3000) + '/api/health').then((r) => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"

# server.js is generated by `next build` from the standalone output.
CMD ["node", "server.js"]
